### ISSUE TITLE
Add HTML index for Alumnos

### ISSUE THREAD

**Issue by eparejatobes** [doplanning/si-eso#67]
This should have

1. an intro text describing the app, instructions
2. links in the navbar for: main adolescentes questionnaire, others (Ejercicio físico, right?)

**Comment by laughedelic** [comment]
As I understand, Alumnos don't have a special introduction. There is some introductory text on the 1st page of their questionnaire though. So after sign-in they are redirected there (see https://github.com/doplanning/si-eso/pull/61#issuecomment-293745175)
